# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-06-11 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_profile_telefono2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='telefono',
        ),
    ]
