# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-06-11 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_remove_profile_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telefono',
            field=models.CharField(default=5453543534, max_length=15),
            preserve_default=False,
        ),
    ]
