# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-06-11 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_profile_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='timestamp')),
                ('lat', models.FloatField(verbose_name='lattitude')),
                ('lon', models.FloatField(verbose_name='longitude')),
            ],
        ),
    ]
