# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-03-11 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_gps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egresados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellidoPaterno', models.CharField(blank=True, max_length=30)),
                ('apellidoMaterno', models.CharField(blank=True, max_length=30)),
                ('genero', models.CharField(blank=True, max_length=30)),
                ('carrera', models.CharField(blank=True, max_length=30)),
                ('medio', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Gps',
        ),
    ]
