# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-03-21 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_auto_20190310_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minuta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiporeunion', models.CharField(max_length=30)),
                ('titulo', models.CharField(blank=True, max_length=30)),
                ('lista_asistencia', models.CharField(blank=True, max_length=30)),
                ('puntos', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
