# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-03-27 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_minuta'),
    ]

    operations = [
        migrations.AddField(
            model_name='egresados',
            name='generacion',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
